export const series = [
  { slug: "scarlet-violet", name: "Scarlet & Violet" },
  { slug: "sword-shield", name: "Sword & Shield" },
  { slug: "sun-moon", name: "Sun & Moon" },
  { slug: "xy", name: "XY" },
  { slug: "black-white", name: "Black & White" },
  { slug: "heartgold-soulsilver", name: "HeartGold & SoulSilver" },
  { slug: "platinum", name: "Platinum" },
  { slug: "diamond-pearl", name: "Diamond & Pearl" },
  { slug: "ex", name: "EX" },
  { slug: "np", name: "NP" },
  { slug: "base", name: "Base" },
  { slug: "e-card", name: "E-Card" },
  { slug: "pop", name: "POP" },
  { slug: "neo", name: "Neo" },
  { slug: "gym", name: "Gym" },
  { slug: "other", name: "Other" },
];
